### ISSUE TITLE
Wicked Edge of the Planes (and precursors) in OH

### ISSUE THREAD

**Issue by VincentVancalbergh** [TheGroxEmpire/TBC_DPS_Warrior_Sim#105]
Dragonstrike and precursors are selectable, please add the Axesmith variants

**Comment by TheGroxEmpire** [comment]
Added in 99cb6b2. Thanks for the request!

**Comment by VincentVancalbergh** [comment]
Thanks!
But... are they also considered in evaluating upgrades? I have Wicked Edge + Merciless Cleaver (S2) and when I sim with "suggest weapon upgrades" it doesn't mention Wicked Edge in OH (upgrade OR downgrade). But when I sim 2 x Wicked Edge it's a dps increase!

**Comment by TheGroxEmpire** [comment]
> Thanks! But... are they also considered in evaluating upgrades? I have Wicked Edge + Merciless Cleaver (S2) and when I sim with "suggest weapon upgrades" it doesn't mention Wicked Edge in OH (upgrade OR downgrade). But when I sim 2 x Wicked Edge it's a dps increase!

Hmm they should be, I will be looking at it then.
