### ISSUE TITLE
The Decapitator

### ISSUE THREAD

**Issue by Othok** [TheGroxEmpire/TBC_DPS_Warrior_Sim#106]
Hello,

is it possible to add [The Decapitator]([https://tbc.wowhead.com/item=28767/the-decapitator) as an option for the off-hand.
The weapon was changed from main hand to one hand in the Zul Aman patch.

Thank you !

**Comment by Shanoga** [comment]
This is also true of Fool's Bane. I know it's kinda garbo, but would appreciate the option to sim these as I potentially switch from Prot to Fury. Thanks!

**Comment by TheGroxEmpire** [comment]
Both are added in the sim now in 5a405b6.
