### ISSUE TITLE
Sword from Magister Terrace Heroic Dungeon for kebab [Quickening Blade of the Prince]

### ISSUE THREAD

**Issue by 19066** [TheGroxEmpire/TBC_DPS_Warrior_Sim#116]
Can update this sword [Quickening Blade of the Prince] from Phase 5 for kebab warriors?

**Comment by colonelsevendot** [comment]
@19066

.\wow_library\include\Armory.hpp / add:
`{"quickening_blade_of_the_prince", Attributes{0.0, 0.0}, Special_stats{0, 0, 38.0, 0.00, 0, 0, 0, 0, 0, 0, 0, 0.0, 0, 0, 0, 126}, 1.5, 96, 180, Weapon_socket::one_hand, Weapon_type::sword},`

.\website\index.html / add x2 main hand & off hand:
`<option value="quickening_blade_of_the_prince"> Quickening Blade of the Prince</option>`

Recompile.
