### ISSUE TITLE
Glancing penalty is wrong vs. level 72 or 71 mobs

### ISSUE THREAD

**Issue by vigo2** [TheGroxEmpire/TBC_DPS_Warrior_Sim#27]
glancing penalty is calculated as `glancing_penalty = 25.0 - (15.0 - level_difference * 5)` vs. 73/72/71 mobs, resulting in 25/20/15%. it's actually 25/15/5%.

**Comment by TheGroxEmpire** [comment]
Thanks for noticing, his was something that left from the vanilla classic sim. I'll have it fixed on the next update (1.0.4).
