### ISSUE TITLE
Rage generation for dodged/parried white hits is wrong

### ISSUE THREAD

**Issue by vigo2** [TheGroxEmpire/TBC_DPS_Warrior_Sim#28]
Dodges and parries on white hits generate rage exactly as if they were regular hits (same "rage range"). The sim is using a 75% multiplier.

**Comment by TheGroxEmpire** [comment]
This was something that came from the classic vanilla sim. What would be the correct way to do it?

**Comment by vigo2** [comment]
The correct way would be to use `hit_outcome.damage` for rage calculation when dodged, basically removing the 75% multiplier.
I've tested it on the PTR, with a 58 druid and a 58 warrior vs. a level 60 dummy: druid white hits yielded 7 to 9 rage, and that's exactly the range for dodges and parries (the "rage range" depending on damage range). The warrior attacked with a 4-6 damage 3.2 speed mace (nearly flat damage), and consistently got 8 rage on hits w/o, and 9 rage on hits w/ battle shout. The same rage values were seen on dodges and parries. (Interestingly, you gain more rage on dodges and parries than on glancing blows.)
I didn't test extensively, but a 75% multiplier can be ruled out, nonetheless.

**Comment by TheGroxEmpire** [comment]
Looks like you're correct. I tested it on beta not using any weapon and the rage is consistent (5 rage) on hit regardless if it's hit, miss, or parry. Thanks for reporting this. This will go live with the (1.0.4) update
