### ISSUE TITLE
Crit Multiplier is wrongly calculated if bonus crit multiplier > 0 (RED)

### ISSUE THREAD

**Issue by vigo2** [TheGroxEmpire/TBC_DPS_Warrior_Sim#30]
The sim calculates it as `(2 + crit_damage_bonus) * (1 + bonus_crit_multiplier)`, where e.g. crit_damage_bonus is 20% for 2/2 Impale, and bonus_crit_multiplier is 3% for RED.
It's actually (and weirdly) calculated as '1 + (1 + crit_damage_bonus) * (2 * (1 + bonus_crit_multiplier) - 1)`. For warriors, the difference is rather miniscule (e.g. 2.266 vs. 2.272), for casters with 100% crit_damage_bonus, it's 2.06 vs 2.09.

**Comment by TheGroxEmpire** [comment]
The crit multiplier is calculated with the multiplicative addition equation as follows:
```
(1 + A) * (1 + B) - 1 = multiplier

// in attributes.cpp
double multiplicative_addition(double val1, double val2)
{
    return (1 + val1) * (1 + val2) - 1;
}
```
In the case of 2/2 impale and 3% crit the total crit damage multiplier will compute as follows:
```
1 + (1 + (1 + 0.2)) * (1 + 0.03) - 1) = 2.266

// in combat_simulator.cpp
damage_multipliers_yellow_ =
            create_multipliers(1.0, 0.1 * config.talents.impale, special_stats.crit_multiplier);

std::vector<double> create_multipliers(double glancing_factor, double crit_damage_bonus, double bonus_crit_multiplier)
{
    // Order -> Miss, parry, dodge, block, glancing, crit, hit.
    return {0.0, 0.0, glancing_factor, 1.0 + multiplicative_addition(1.0 + crit_damage_bonus, bonus_crit_multiplier),
            1.0};
}
```

**Comment by vigo2** [comment]
`multiplicative_addition()` is fine for stacking regular damage multipliers, or even crit damage multipliers, but not for the way crit bonus damage interacts with the regular damage multiplier.

from https://web.archive.org/web/20081014064638/http://elitistjerks.com/f31/t12595-relentless_earthstorm_diamond_-_melee_only/p4/

> After mucking around and doing some calculations, I came up with a nice summary of how the RED works:
>
>100% + {(150%*1.03) - 100%} * (100% + TDI) = Crit Damage
>Where
>
>100% is the normal damage
>
>{(150%*1.03) - 100%} is the crit damage with the relentless earthstorm diamond (would normally be 150% - >100% or simply 50%). This would be {(200% * 1.03) - 100%) for melee damage.
>
>(100% + TDI) is the total damage increased from talents, with TDI as the percent increase from talents (100% for >ele shammies using Elemental Fury, Locks using Ruin, Moonkin using Vengeance; 50% for arcane mages using >spell power; 30% for rogues using lethality; etc)
>
>For simplicity's sake, here's a list of crit damage increase from the Relentless Earthstorm Diamond:
>
>(Note that Ignite is not a crit modifier – it just multiplies the total damage done by 1.4. Ignite is also included in >the final crit damage %)
>
>
>Moonkin: 209% - 200% = 9%
>Feral Druid: 216.6% - 210% = 6.6%
>
>Marksmanship Hunter: 237.8% - 230% = 7.8%
>
>Arcane Mage: 181.75% - 175% = 6.75%
>Arcane/Frost Mage: 236.25% -225% = 11.25%
>Fire Mage: 216.3% - 210% = 6.3%
>Arcane/Fire mage: 254.45% - 245% = 9.45%
>
>Lethality Rogue: 237.8% - 230% = 7.8%
>
>Elemental Shaman: 209% - 200% = 9%
>
>Ruin Warlock: 209% - 200% = 9%
>
>Arms Warrior: 220% - 227.2% = 7.2%

I've recently analyzed a Brutallus video, and BTs crit/non-crit damage values match that 2.272 multiplier exactly. Other people have encountered the quoted values as well.

**Comment by TheGroxEmpire** [comment]
I'm trying to verify this on dummy in beta but the crit number is all over the place and I could confirm nothing.
With RED:
Bloodthirst = ``1185 crit`` and ``539 normal`` (1212 AP)
Hamstring = ``137 crit`` and ``63`` normal

Without RED:
Bloodthirst = ``1171 crit`` and 11532 normal (1197 AP)
Hamstring = ``137 crit`` and ``63`` normal

Until I could get confirmation that this is how it actually work on current TBCC I'll keep it as it is.

**Comment by vigo2** [comment]
Were the REDs socket requirements fulfilled? These are all ~220% modifiers. White damage should have 206% crits - https://tbc.wowhead.com/item=2480/large-club is good for testing.

**Comment by TheGroxEmpire** [comment]
> Were the RED's socket requirements fulfilled? These are all ~220% modifiers. White damage should have 206% crits - https://tbc.wowhead.com/item=2480/large-club is good for testing.

Yes, the talent used were impale and RED. And they seems to be similar with impale and non RED. I tested white damage with unarmed which also has 1-2 damage range and the results are pretty similar for both (Mainly because the number is super miniscule for 3% extra crit to be miniscule) So I tried testing it with BT.

**Comment by vigo2** [comment]
There has been some testing in the rogue discord (around here: https://discord.com/channels/253211161850281995/812965447766245427/837058046672764990), and in the warlock discord as well (with the caster variant, Chaotic Skyfire Diamond), both agree with the numbers from EJ post above. The 2.09x multiplier for warlocks has even made it to wowhead ;)

At 1400 AP, the 3.2 speed Large Club above deals 325 damage, 650 crit, and ~670 crit w/ RED (x2.06). If the result are indeed pretty similar now, RED is either bugged now or doesn't meet its requirements. From my very limited experience, it helps to sunder the dummy, so it's actually at 0 armor.

(I'm fully aware that 0.6% additional damage on crit is rather meaningless, so sorry for blowing this most inconsequential of issues out of proportion.)

**Comment by TheGroxEmpire** [comment]
I'll have this tested more thoroughly on beta in the future. It's totally fine to bring this up, but since it is really miniscule it'll not be on the priority for now.

**Comment by vigo2** [comment]
Using BT on a fully sundered test dummy, I had BT hits for 854-855 (40+ samples), and BT crits for 1941-1942 (10 samples). Smaller samples hat BT hits/crits at 1000/2272 (AP proc), and 889/2019 (Blood Frenzy).
All results fit a 227.2% multiplier, and are slightly off for 226.6% (854-855 -> 1935.1-1937.4).

**Comment by TheGroxEmpire** [comment]
I guess that's it. I'll have `(2 + crit_damage_bonus) * (1 + bonus_crit_multiplier)` changed to `1 + (1 + crit_damage_bonus) * (2 * (1 + bonus_crit_multiplier) - 1)`
Alongside P2 item update. Thanks for doing the test

**Comment by vigo2** [comment]
You can just toggle the formulae in Combat_simulator.cpp::362 ;)

**Comment by TheGroxEmpire** [comment]
> You can just toggle the formulae in Combat_simulator.cpp::362 ;)

Thanks. It is now live on f6e7c04. The damage increase is bigger than I thought. Using P1 Fury BiS preset I am seeing ``1171.39 ± 1.08`` DPS compared to ``1159.43 ± 1.08`` DPS on previous multiplier formula.
