### ISSUE TITLE
Rage generation for crits is too low

### ISSUE THREAD

**Issue by vigo2** [TheGroxEmpire/TBC_DPS_Warrior_Sim#31]
`rage_generation()` is using the same "hit_factor" for hits and crits (3.5 for MH / 1.75 for OH). It should use 7 for MH / 3.5 for OH on crits.

**Comment by TheGroxEmpire** [comment]
After further testing on beta, I did found that the ``hit_factor`` doubling for crit was indeed totally right. This change will live on (1.0.4) thanks for reporting!
