### ISSUE TITLE
Heroic Strike/Cleave are re-queued too early

### ISSUE THREAD

**Issue by vigo2** [TheGroxEmpire/TBC_DPS_Warrior_Sim#32]
`swing_weapon()` is used for regular weapon swings and for extra attacks from Windfury and other weapon procs.

Among other things, it may convert white attacks into HS/Cleave, then re-queue them if sufficient rage is available. Afterwards, it handles the various "hit effects", and if any of them grant extra attacks, those are converted into HS/Cleave, again. This is generally impossible to do in-game.

**Comment by TheGroxEmpire** [comment]
As of today's build, this is not the case. Windfury / extra attack that was procced from Heroic Strike doesn't grant Heroic Strike for the extra attack. This was proven by the combat log in the sim:

```
Time: 7.200040s. Event: Performing Heroic Strike
Time: 7.200040s. Event: Drawing outcome from yellow table
Time: 7.200040s. Event: Ability hit for: 1314 damage.
Time: 7.200040s. Event: Current rage: 88
Time: 7.200040s. Event: 0 flurry charges
Time: 7.200040s. Event: PROC: lionheart_champion stats increased for 10s
Time: 7.200040s. Event: PROC: extra hit from: windfury_totem
Time: 7.200040s. Event: Drawing outcome from MH hit table
Time: 7.200040s. Event: Mainhand crit for: 2564 damage.
Time: 7.200040s. Event: Current rage: 100
Time: 7.200040s. Event: 3 flurry charges
Time: 7.200040s. Event: Unbridled wrath. Current rage: 100
Time: 7.200040s. Event: Unbridled wrath. Current rage: 100
Time: 7.200040s. Event: Heroic strike activated
Time: 10.800050s. Event: Performing Heroic Strike
Time: 10.800050s. Event: Drawing outcome from yellow table
Time: 10.800050s. Event: Ability hit for: 1379 damage.
```

**Comment by vigo2** [comment]
This was assuming the
```
        if (config.ability_queue_ && rage > config.ability_queue_rage_thresh_)
        {
            simulator_cout("Re-queue Heroic Strike!");
            ability_queue_manager.queue_heroic_strike();
        }
```
branch would be taken - or is that effectively dead code since the above config options are never set?

**Comment by vigo2** [comment]
Talking of probably unused config options, `config.dpr_settings.compute_dpr_hs_` looks pretty fishy: if it's set `dpr_heroic_strike_queued_` is set in simulate(), then later in swing_weapon() there's
```
        // Otherwise do white hit
        hit_outcomes.emplace_back(generate_hit(main_hand_weapon, swing_damage, Hit_type::white, weapon.socket,
                                               special_stats, damage_sources));
        if (dpr_heroic_strike_queued_)
        {
            rage -= heroic_strike_rage_cost;
            dpr_heroic_strike_queued_ = false;
        }
```
in a place where `rage >= heroic_strike_rage_cost` hasn't been verified (since, weirdly, if `dpr_heroic_strike_queued_` is set in this way, no HS is queued). An equivalent set of variables exists for Cleave.

**Comment by TheGroxEmpire** [comment]
> ability_queue_

This config is used to perform what is called HS queueing. Where players would Queue HS above certain rage and cancel it below certain rage when MH is about to hit. This technique was fascinated during Classic vanilla to remove DW penalty on OH. It wasn't a really popular technique and it would see much less use on TBCC also.

**Comment by TheGroxEmpire** [comment]
> Talking of probably unused config options, `config.dpr_settings.compute_dpr_hs_` looks pretty fishy: if it's set `dpr_heroic_strike_queued_` is set in simulate(), then later in swing_weapon() there's
> 
> ```
>         // Otherwise do white hit
>         hit_outcomes.emplace_back(generate_hit(main_hand_weapon, swing_damage, Hit_type::white, weapon.socket,
>                                                special_stats, damage_sources));
>         if (dpr_heroic_strike_queued_)
>         {
>             rage -= heroic_strike_rage_cost;
>             dpr_heroic_strike_queued_ = false;
>         }
> ```
> 
> in a place where `rage >= heroic_strike_rage_cost` hasn't been verified (since, weirdly, if `dpr_heroic_strike_queued_` is set in this way, no HS is queued). An equivalent set of variables exists for Cleave.

Indeed. This is the way sims calculate the DPR. First the sim would run normal simulations. After that, the sim would also run simulations where the ability that the DPR is being calculated still cost rage but does zero effect. The sim would compare the average of damage of those two and divide it with their respective rage cost on each ability DPR. This way both normal simulation and DPR simulation maintains the same rotation, the only differing part is that the DPR simulation ability only reduces rage and does no effect.

**Comment by TheGroxEmpire** [comment]
As this issue is confirmed to be not valid. I'll close this issue. Further issue could be made on another Issues post. Thanks!
