### ISSUE TITLE
Sword spec extra attacks are not converted into Heroic Strike/Cleave

### ISSUE THREAD

**Issue by vigo2** [TheGroxEmpire/TBC_DPS_Warrior_Sim#33]
Sword spec extra attacks are using `sword_spec_hit()` instead of `weapon_swing()` to model their extra attack, which basically omits Heroic Strike/Cleave handling. In-game, such extra attacks can be converted into Heroic Strike/Cleave, see https://github.com/magey/tbc-warrior/issues/5.

**Comment by TheGroxEmpire** [comment]
Thanks for the report. ``sword_spec_hit()`` usage has been deprecated and sword spec extra attacks will use ``swing_weapon()`` function starting on ~~1.0.4~~ 1.1.0 (1.0.4 has been renamed to 1.1.0 as there has been numerous changes made on that patch branch)
