### ISSUE TITLE
Swing timers are not updated directly when you gain Flurry, or when Flurry fades

### ISSUE THREAD

**Issue by vigo2** [TheGroxEmpire/TBC_DPS_Warrior_Sim#35]
The swing timer is only updated in swing_weapon() (Combat_simulator.cpp:1087), so Flurry gains are only applied on the next MH or OH swing, effectively hasting first one, then the other. If Flurry fades, the haste loss is handled in the same way.

In game, both gaining or losing Flurry immediately updates the swing timers for both weapons, e.g. for a 2.6 speed MH, if WW procs Flurry exactly mid-swing, the next MH hit is 1.3 + 1.3 / 125% = 2.34 seconds after the first. If Flurry faded 0.8 seconds after a swing, the next MH hit would be 0.8 + (2.6 / 125% - 0.8) * 125% = 2.4 seconds later.

**Comment by TheGroxEmpire** [comment]
A similar issue was described on WoW Fury Sim discord where haste from ``hit_effect`` is only applied on the next MH. I fixed that issue by resetting the swing timer after ``hit_effect`` is resolved. That fix will be live on 1.1.0 and will fix this issue also. Thanks for the report.
