### ISSUE TITLE
The Decapitator missing

### ISSUE THREAD

**Issue by ptollo** [TheGroxEmpire/TBC_DPS_Warrior_Sim#36]
I wanted to look which weapon is strongest for my fury warrior and noticed that "The Decapitator" from Prince Malchezzar in Karazhan seems to be missing.

**Comment by TheGroxEmpire** [comment]
Can you please clarify on what is missing? The Decapitator seems to exist on the sim.

**Comment by ptollo** [comment]
My bad, this report can be closed.
I always forget that The Decapitator is main-hand only on TBC classic and tryed to find him in the off-hand category.
