### ISSUE TITLE
Some player buffs are using talented, others untalented values

### ISSUE THREAD

**Issue by vigo2** [TheGroxEmpire/TBC_DPS_Warrior_Sim#38]
Namely, Blessing of Might (220 AP -> 264 AP) and Gift of the Wild (14 Agi/Str -> 18.9 Agi/Str) are using talented values, while Battle Shout (306 AP -> 382.5 AP) and all Shaman totems (WF 445 AP -> 578.5 AP; 86 Str -> 98.9 Str; 77 Agi -> 88.55 Agi) are using untalented values.

**Comment by TheGroxEmpire** [comment]
- Battle shout are affected player's Commanding Presence talent
- Shaman totems are affected by ``improved_weapon_totems`` and ``enhancing_totems`` option

**Comment by vigo2** [comment]
Sorry, these usages didn't show up in my IDE. I guess I changed to the 1.1.0 branch without reloading the project proper.
