### ISSUE TITLE
Flurry grants too much attack speed (30% instead of 25%)

### ISSUE THREAD

**Issue by vigo2** [TheGroxEmpire/TBC_DPS_Warrior_Sim#41]
The `flurry_haste_factor_` is calculated as `(config.talents.flurry > 0) ? 0.05 + 0.05 * config.talents.flurry : 0.0;`; it should just be `0.05 * config.talents.flurry`.

**Comment by TheGroxEmpire** [comment]
Nice find! Fixed in 25943e7.
