### ISSUE TITLE
Issue #35 has not been fixed

### ISSUE THREAD

**Issue by vigo2** [TheGroxEmpire/TBC_DPS_Warrior_Sim#42]
Issue #35 still persists exactly as described - flurry haste is still only recalculated in `swing_weapon()`, at end of swing, for each weapon individually. It should be recalculated mid-swing, for both weapons at once.

In a similar vein, calculating flurry uptime via `mh_hits_w_flurry` and `oh_hits_w_flurry` doesn't make much sense, since swings may be partially hasted.

**Comment by TheGroxEmpire** [comment]
Hmm yea, this is requiring some overhaul on how the flurry is applied. I'll put this on TO-DO for now.
