### ISSUE TITLE
Waste Walker 2 set Bonus

### ISSUE THREAD

**Issue by Draegor** [TheGroxEmpire/TBC_DPS_Warrior_Sim#47]
It doesn't appear that the waste walker 2 set bonus is being taken into account.

![image](https://user-images.githubusercontent.com/87884121/126853604-b165a013-60b4-4916-9a99-122a97ea74c2.png)
![image](https://user-images.githubusercontent.com/87884121/126853673-60d24aa1-3bbc-4729-914a-f517fd651200.png)

**Comment by TheGroxEmpire** [comment]
The Wastewalker set was in the sim, but it misses some pieces like helm and shoulder to be accounted into the set. It has now been fixed in 85b1181
