### ISSUE TITLE
Very low amount of items in selection?

### ISSUE THREAD

**Issue by hasnogaems** [TheGroxEmpire/TBC_DPS_Warrior_Sim#50]
Can I manually add more?

**Comment by ghronkrepps** [comment]
Feltooth Eviscerator Dagger from Heroic Ramparts is missing.

**Comment by TheGroxEmpire** [comment]
> Feltooth Eviscerator Dagger from Heroic Ramparts is missing.

Added in f851cca.

**Comment by hasnogaems** [comment]
Maybe you can add "custom item" option to every slot, with customisable stats?
