### ISSUE TITLE
Incorrect PPM for Despair and Khorium Champion

### ISSUE THREAD

**Issue by Razorwynd** [TheGroxEmpire/TBC_DPS_Warrior_Sim#64]
Didn't get much time tonight to test PPM for these two weapons (30 min of only auto-attacks) but both appear to be lower than 1 PPM. Although it shouldn't matter much with new content around the corner.
KC test one 14/ 717 (not logged)
Despair test one 11/336 (not logged)
KC test two 18/605 (log attached)
Despair test two 13/559 (log attached)

prelim KC PPM = 32/1322 = 2.4% per swing
prelim despair PPM = 24/895 = 2.7% per swing
[Despair.txt](https://github.com/TheGroxEmpire/TBC_DPS_Warrior_Sim/files/7110969/Despair.txt)
[KhoriumChampion.txt](https://github.com/TheGroxEmpire/TBC_DPS_Warrior_Sim/files/7110970/KhoriumChampion.txt)

**Comment by TheGroxEmpire** [comment]
Thank you for doing the test and providing with the data, it has now been fixed in bc355e6.
