### ISSUE TITLE
Direbrew's Shanker

### ISSUE THREAD

**Issue by massibronto** [TheGroxEmpire/TBC_DPS_Warrior_Sim#72]
Hey,

I would like to know if it's worth to enchant Direbrew's Shanker with Mungo.
Can you please add this item into the Sim?:
https://tbc.wowhead.com/item=37597/direbrews-shanker

Best regards and keep up the great work. :-)

**Comment by TheGroxEmpire** [comment]
I added Emerald Ripper which has the same stats in 5a15f50
