### ISSUE TITLE
2 missing Ogri'la items

### ISSUE THREAD

**Issue by Chanizu** [TheGroxEmpire/TBC_DPS_Warrior_Sim#73]
[Crystalforged trinket - Revered](https://tbc.wowhead.com/item=32654/crystalforged-trinket)
[Crystalline Crossbow - Exalted](https://tbc.wowhead.com/item=32645/crystalline-crossbow)

**Comment by boktai1000** [comment]
May also want to add Crystalweave Cape, comes from Depleted Cloak.

![image](https://user-images.githubusercontent.com/9054563/135764664-10d3086d-98cd-491a-b102-c10a82160b2e.png)


https://tbc.wowhead.com/item=32665/crystalweave-cape

**Comment by TheGroxEmpire** [comment]
Added all of them in 5a15f50
