### ISSUE TITLE
No way to force bloodlust at the start of the fight?

### ISSUE THREAD

**Issue by Speaker1264** [TheGroxEmpire/TBC_DPS_Warrior_Sim#88]
Is there no way to force bloodlust to be cast at the start of the fight instead of the end or am I missing the option?  I see the option for extra bloodlusts being cast at the start, but I don't want to add extra bloodlusts, only 1 bloodlust for the whole fight.

**Comment by TheGroxEmpire** [comment]
There is a way for it. If you only use the extra_bloodlust without the normal bloodlust you'll only have 1 bloodlust.
