### ISSUE TITLE
Missing Hyjal item 

### ISSUE THREAD

**Issue by hsus8** [TheGroxEmpire/TBC_DPS_Warrior_Sim#92]
The Unbreakable Will from Hyjal is missing from the one handed swords category.

Link to the item: [https://tbc.wowhead.com/item=30874/the-unbreakable-will](https://tbc.wowhead.com/item=30874/the-unbreakable-will)

**Comment by TheGroxEmpire** [comment]
@hsus8 This item has been added few days ago in 8f96ba3.
